paths:
  /origins:
    get:
      tags:
        - origins
      summary: Returns a list of coffee origins.
      responses:
        '200':
          description: A list of coffee origins.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Origin'
    post:
      tags:
        - origins
      summary: Creates a coffee origin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Origin'
      responses:
        '200':
          description: OK
  /origins/{originId}:
    put:
      tags:
        - origins
      summary: Updates a coffee origin by id.
      parameters:
        - name: originId
          in: path
          required: true
          description: The unique identifier of the origin.
          schema:
            type : string
      responses:
        '200':
          description: OK
    get:
      tags:
        - origins
      summary: Gets a coffee origin by id
      parameters:
        - name: originId
          in: path
          required: true
          description: The unique identifier of the origin.
          schema:
            type : string
      responses:
        '200':
          description: The coffee origin by id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Origin'
    delete:
      tags:
        - origins
      summary: Deletes a coffee origin by id
      parameters:
        - name: originId
          in: path
          required: true
          description: The unique identifier of the origin.
          schema:
            type : string
      responses:
        '200':
          description: OK
