paths:
  /crops:
    get:
      tags:
        - crops
      summary: Returns a list of coffee crops.
      responses:
        '200':
          description: A list of coffee crops.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Crop'
    post:
      tags:
        - crops
      summary: Creates a coffee crop
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Crop'
      responses:
        '200':
          description: The created crop
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Crop'
  /crops/{cropId}:
    put:
      tags:
        - crops
      summary: Updates a coffee crop by id.
      parameters:
        - name: cropId
          in: path
          required: true
          description: The unique identifier of the crop.
          schema:
            type : string
      responses:
        '200':
          description: The updated crop
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Crop'

    get:
      tags:
        - crops
      summary: Gets a coffee crop by id
      parameters:
        - name: cropId
          in: path
          required: true
          description: The unique identifier of the crop.
          schema:
            type : string
      responses:
        '200':
          description: The coffee crop by id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Crop'
    delete:
      tags:
        - crops
      summary: Deletes a coffee crop by id
      parameters:
        - name: cropId
          in: path
          required: true
          description: The unique identifier of the crop.
          schema:
            type : string
      responses:
        '200':
          description: OK
