paths:
  /roasts:
    get:
      tags:
        - roasts
      summary: Returns a list of coffee roasts.
      responses:
        '200':
          description: A list of coffee roasts.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Roast'
    post:
      tags:
        - roasts
      summary: Creates a new coffee roast.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Roast'
      responses:
        '200':
          description: OK
  /roasts/{roastId}:
    get:
      tags:
        - roasts
      summary: Returns a single roast by id.
      parameters:
        - name: roastId
          in: path
          required: true
          description: The unique identifier of the roast.
          schema:
            type: string
      responses:
        '200':
          description: A single coffee roast by id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Roast'
    put:
      tags:
        - roasts
      summary: Updates a coffee roast by id.
      parameters:
        - name: roastId
          in: path
          required: true
          description: The unique identifier of the roast.
          schema:
            type: string
      responses:
        '200':
          description: OK
    delete:
      tags:
        - roasts
      summary: Deletes a coffee roast by id.
      parameters:
        - name: roastId
          in: path
          required: true
          description: The unique identifier of the roast.
          schema:
            type: string
      responses:
        '200':
          description: OK
